<div class="container">
    <div class="row">
        <div class="span4">
            <ul style="list-style: none;">
                <li>
                    <a href="<?php echo $this->url("zfcadmin/wdg-blog-admin/category/list");?>">
                        Manage Categories
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url("zfcadmin/wdg-blog-admin/post/list");?>">
                        Manage Posts
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>