<div class="container">
    <div class="row">
        <div class="offset2 span4">
            <a href="<?php echo $this->url("zfcadmin/wdg-blog-admin/category/list");?>"><i class="icon-folder-open icon-4x"> Categories</i></a>
        </div>
        <div class="offset2 span4">
            <a href="<?php echo $this->url("zfcadmin/wdg-blog-admin/post/list");?>"><i class="icon-file icon-4x"> Posts</i></a>
        </div>
    </div>
</div>