<ul class="breadcrumb">
    <li><a href="<?php echo $this->url("wdgadmin");?>">Dashboard</a> <span class="divider">/</span></li>
    <li class="active">Blog</li>
</ul>
<div class="container">
    <div class="row">
        <div class="offset2 span4">
            <a href="<?php echo $this->url("wdgadmin/blog_category_list");?>"><i class="icon-folder-open icon-4x"> Categories</i></a>
        </div>
        <div class="offset2 span4">
            <a href="<?php echo $this->url("wdgadmin/blog_post_list");?>"><i class="icon-file icon-4x"> Posts</i></a>
        </div>
    </div>
</div>