<?php $this->headTitle()->append("Blog Post"); ?>

<h1><?php echo $this->translate('Blog Post') ?></h1>

<ul class="nav nav-tabs" id="blogPostTabs" style="margin-bottom:10px">
    <li class="active"><a href="#tab_info">Info</a></li>
    <li><a href="#tab_categories">Categories</a></li>
</ul>
<div class="tab-content">
    <div class="tab-pane active" id="tab_info">
        <div class="navbar filter-bar">
            <div class="navbar-inner">
                <div class="pull-right">
                    <a href="<?php echo $this->url('zfcadmin/wdg-blog-admin/post/edit', array('id' => $this->post->getId())) ?>" class="btn btn-primary">
                        <?php echo $this->translate('Edit Post') ?>
                    </a>
                </div>
            </div>
        </div>
        <?php 
        $values = array(
            "Id" => $this->post->getId(),
            "Title" => $this->post->getTitle(),
            "Slug" => $this->post->getSlug(),
            "Thumbnail" => $this->post->getThumbnailHtml()." ".$this->post->getThumbnail(),
            "Thumbnail Alt" => $this->post->getThumbnailAlt(),
            "Author" => $this->post->getAuthor()->getDisplayName(),
            "Created" => $this->post->getCreated()->format("m-d-Y"),
            "Excerpt" => $this->post->getExcerpt(),
            "Body" => $this->post->getBody()
        );

        $count  = count($values);
        $i      = 0;
        
        foreach($values as $label => $value)
        {
            $i++;
            ?>
            <label class="text-info"><?php echo $label;?>:</label>
            <?php 
            echo $value;
            
            if($i !== $count)
                echo "<hr />";
        }
        ?>
    </div>
    <div class="tab-pane" id="tab_categories">
        <div class="navbar filter-bar">
            <div class="navbar-inner">
                <div class="pull-right">
                    <a href="<?php echo $this->url('zfcadmin/wdg-blog-admin/post/categories', array('id' => $this->post->getId())) ?>" class="btn btn-primary">
                        <?php echo $this->translate('Manage Categories') ?>
                    </a>
                </div>
            </div>
        </div>
        <div>
            <ul>
            <?php
            $categories = $this->post->getCategories();

            if(count($categories) > 0)
            {
                foreach ($categories as $category) 
                {
                    echo "<li>".$category->getName()."</li>";
                }
            }
            else echo "<li>No categories</li>";
            ?>
            </ul>
        </div>
    </div>
</div>

<div class="clearfix"></div>
<?php
$script = $this->inlineScript();
$script->appendScript(<<<'EOT'
    
    $("#blogPostTabs a").click(function (e) {
        e.preventDefault();
        $(this).tab("show");
    });
    
EOT
);
